import { internalMutation } from "./_generated/server";

// Internal mutation to add a single course
export const addCourse = internalMutation({
    args: {},
    handler: async (ctx) => {
        const courses = [
            { code: "ACCT-100", name: "Principles of Financial Accounting" },
            { code: "ACCT-130", name: "Principles of Management Accounting" },
            { code: "ACCT-220", name: "Corporate Financial Reporting I" },
            { code: "ACCT-250", name: "Auditing" },
            { code: "ACCT-320", name: "Corporate Financial Reporting II" },
            { code: "ACCT-362", name: "Fraud Examination and Forensic Accounting" },
            { code: "ACCT-370", name: "Applied Taxation" },
            { code: "ACCT-411", name: "Applied Financial Analysis" },
            { code: "ACF-5101", name: "Financial Management and Accounting" },
            { code: "AI-600", name: "Deep Learning" },
            { code: "AI-620", name: "Fundamentals of Data Engineering" },
            { code: "AI-621", name: "MLOps, LLMOps, and Agentic AI Systems" },
            { code: "AI-623", name: "Deep Vision-Language Models" },
            { code: "AI-641", name: "Think, Learn, Move: AI for Robotics" },
            { code: "ANTH-100", name: "Introduction to Cultural Anthropology" },
            { code: "ANTH-263", name: "Food and Culture" },
            { code: "ANTH-310", name: "Classical Anthropological Theory" },
            { code: "ANTH-423", name: "World Through a Trickster's Eyes" },
            { code: "AST-104", name: "The Universe Around Us" },
            { code: "BIO-100", name: "Biology Laboratory" },
            { code: "BIO-101", name: "Introductory Biology" },
            { code: "BIO-212", name: "Biochemistry" },
            { code: "BIO-231", name: "Computational Biology I" },
            { code: "BIO-314", name: "Virology and Microbiology" },
            { code: "BIO-402", name: "Seminar in Biology II" },
            { code: "BIO-415", name: "Developmental Biology I" },
            { code: "BIO-512", name: "Advance Biochemistry" },
            { code: "BIO-515", name: "Eukaryotic Development" },
            { code: "BIO-522", name: "Topics in Cancer Biology" },
            { code: "BIO-5311", name: "Advanced Biostatistics" },
            { code: "BIO-611", name: "Cell Signaling" },
            { code: "BIO-621", name: "Genetics and Genomics" },
            { code: "CHE-230", name: "Chemical Engineering Thermodynamics" },
            { code: "CHE-412", name: "Membrane Science and Engineering" },
            { code: "CHE-200A", name: "Chemical Engineering Lab I" },
            { code: "CHE-262", name: "Particle Science and Engineering" },
            { code: "CHE-273", name: "Fluid Mechanics" },
            { code: "CHE-300B", name: "Chemical Engineering Lab III" },
            { code: "CHE-300C", name: "Chemical Engineering Lab IV" },
            { code: "CHE-315", name: "Chemical Process Simulation" },
            { code: "CHE-330", name: "Math Methods in Chemical Engineering II" },
            { code: "CHE-360", name: "Chemical Kinetics and Reaction Engineering" },
            { code: "CHE-390", name: "Transport Phenomena" },
            { code: "CHE-413", name: "Process Optimization" },
            { code: "CHE-415", name: "Renewable Energy: Applications and Economics" },
            { code: "CHE-430", name: "Chemical Process Control" },
            { code: "CHE-480", name: "Chemical Process Design II" },
            { code: "CHE-512", name: "Biochemical Engineering" },
            { code: "CHE-710", name: "Transport Processes in the Environment" },
            { code: "CHE-713", name: "Engineering Thermodynamics" },
            { code: "CHEM-100", name: "Experimental Chemistry" },
            { code: "CHEM-230", name: "Organic Chemistry Lab I" },
            { code: "CHEM-233", name: "Molecular Spectroscopy" },
            { code: "CHEM-251", name: "Biochemistry" },
            { code: "CHEM-311", name: "Chemical Thermodynamics" },
            { code: "CHEM-320", name: "Inorganic Chemistry Lab" },
            { code: "CHEM-324", name: "Inorganic Chemistry I" },
            { code: "CHEM-334", name: "Advanced Organic Chemistry" },
            { code: "CHEM-410", name: "Physical Chemistry Lab" },
            { code: "CHEM-503", name: "Experimental Methods in Chemical Research" },
            { code: "CHEM-515", name: "Polymer Science and Technology" },
            { code: "CHEM-533", name: "Organic Spectroscopy" },
            { code: "CLCA-1122", name: "Readings in Urdu Literature" },
            { code: "CLCA-2121", name: "The Pakistani Drama Serial" },
            { code: "CLCA-2128", name: "Partition Literature in Urdu" },
            { code: "CLCA-2135", name: "Modern Urdu Poetics" },
            { code: "CLCA-2223", name: "The Art of Television and Web Series" },
            { code: "CLCA-2310", name: "Fiction Writing Workshop" },
            { code: "CLCA-2402", name: "Book Illustration" },
            { code: "CLCA-2422", name: "Introduction to Sanskrit" },
            { code: "CLCA-3000", name: "Methods in Comparative Literature" },
            { code: "CLCA-3143", name: "Waris Shah's Heer" },
            { code: "CLCA-3211", name: "Film and Media Studies Seminar" },
            { code: "CLCA-3217", name: "Bad Mothers, Motherhood, and Mothering on Screen" },
            { code: "CLCA-3324", name: "The Craft of Translation" },
            { code: "CLCA-3522", name: "The Art of the Cut" },
            { code: "CLCA-3523", name: "Advanced Motion Media Techniques (Animation II)" },
            { code: "CLCA-4403", name: "World Through a Trickster's Eyes" },
            { code: "CS-100", name: "Computational Problem Solving" },
            { code: "CS-1001", name: "Computational Problem Solving with Python" },
            { code: "CS-200", name: "Introduction to Programming" },
            { code: "CS-202", name: "Data Structures" },
            { code: "CS-220", name: "Digital Logic Circuits" },
            { code: "CS-220L", name: "Digital Logic Circuits Lab" },
            { code: "CS-232", name: "Computational Biology I" },
            { code: "CS-300", name: "Advanced Programming" },
            { code: "CS-310", name: "Algorithms" },
            { code: "CS-315", name: "Theory of Automata" },
            { code: "CS-320", name: "Computer Organization and Assembly Language" },
            { code: "CS-326", name: "Mind Matters: The Psychology of Intelligence and AI" },
            { code: "CS-331", name: "Foundations of AI and Machine Learning" },
            { code: "CS-334", name: "Principles and Techniques of Data Science" },
            { code: "CS-360", name: "Software Engineering" },
            { code: "CS-382", name: "Network-Centric Computing" },
            { code: "CS-413", name: "Teaching CS Beyond Campus: Shaping Tech Literacy for Tomorrow" },
            { code: "CS-432", name: "Data Mining Tasks and Techniques" },
            { code: "CS-437", name: "Deep Learning" },
            { code: "CS-464", name: "Compiler Design" },
            { code: "CS-466", name: "Human-Computer Interaction and Design" },
            { code: "CS-473", name: "Network Security" },
            { code: "CS-487", name: "Cloud Development" },
            { code: "CS-5102", name: "Algorithms" },
            { code: "CS-5112", name: "Introduction to Quantum Information Science and Technology" },
            { code: "CS-5302", name: "Foundations of Generative AI" },
            { code: "CS-5305", name: "MLOps, LLMOps, and Agentic AI Systems" },
            { code: "CS-5306", name: "Foundations of AI and Machine Learning" },
            { code: "CS-5312", name: "Big Data Analytics" },
            { code: "CS-5317", name: "Deep Learning" },
            { code: "CS-532", name: "Applied AI" },
            { code: "CS-536", name: "Data Mining Tasks and Techniques" },
            { code: "CS-5603", name: "Cloud Development" },
            { code: "CS-5606", name: "Designing Human-Centered AI" },
            { code: "CS-5607", name: "Compiler Design" },
            { code: "CS-5613", name: "Human-Computer Interaction and Design" },
            { code: "CS-564", name: "Software Development: Tools and Processes" },
            { code: "CS-5714", name: "Network Security" },
            { code: "CS-677", name: "Internet of Things" },
            { code: "DISC-112", name: "Computer and Problem Solving" },
            { code: "DISC-203", name: "Probability and Statistics" },
            { code: "DISC-212", name: "Introduction to Management Science" },
            { code: "DISC-231", name: "Operations Management" },
            { code: "DISC-320", name: "Qualitative and Quantitative Methods in Business" },
            { code: "DISC-321", name: "Decision Analysis" },
            { code: "DISC-322", name: "Optimization Methods in Management Science" },
            { code: "DISC-323", name: "Decision Behaviour" },
            { code: "DISC-325", name: "Business Data Management" },
            { code: "DISC-326", name: "Data Science for Decision Making" },
            { code: "DISC-327", name: "Risk Management Process" },
            { code: "DISC-333", name: "Supply Chain and Logistics Management" },
            { code: "DISC-420", name: "Business Analytics" },
            { code: "DISC-472", name: "Generative AI for Business and Automation" },
            { code: "DISC-8603", name: "Causal Models" },
            { code: "DISC-8604", name: "Machine Learning Models" },
            { code: "DISC-8607", name: "Qualitative Research Methods" },
            { code: "ECON-100", name: "Principles of Economics" },
            { code: "ECON-111", name: "Principles of Microeconomics" },
            { code: "ECON-121", name: "Principles of Macroeconomics" },
            { code: "ECON-211", name: "Intermediate Microeconomics" },
            { code: "ECON-213", name: "Behavioral Economics" },
            { code: "ECON-221", name: "Intermediate Macroeconomics" },
            { code: "ECON-230", name: "Statistics and Data Analysis" },
            { code: "ECON-2301", name: "Data Analytics Lab I" },
            { code: "ECON-233", name: "Introduction to Game Theory" },
            { code: "ECON-240", name: "Development Economics" },
            { code: "ECON-261", name: "Principles of Finance" },
            { code: "ECON-311", name: "Industrial Organisation" },
            { code: "ECON-330", name: "Econometrics" },
            { code: "ECON-3301", name: "Data Analytics Lab II" },
            { code: "ECON-3302", name: "Introduction to Cooperative Game Theory" },
            { code: "ECON-3402", name: "Gender Economics" },
            { code: "ECON-3404", name: "Ethics and Economics" },
            { code: "ECON-3603", name: "Money and Monetary Policy: Applications to Pakistan" },
            { code: "ECON-3604", name: "Bank Financial Management" },
            { code: "ECON-371", name: "Public Economics" },
            { code: "ECON-411", name: "Advanced Microeconomics" },
            { code: "ECON-414", name: "Applied Microeconomics" },
            { code: "ECON-421", name: "Advanced Macroeconomics" },
            { code: "ECON-4303", name: "Causal Inference and Research Design for Policy Evaluation" },
            { code: "ECON-435", name: "Advanced Game Theory" },
            { code: "ECON-4404", name: "Economics of Artificial Intelligence" },
            { code: "ECON-441", name: "Development Economics Theory" },
            { code: "ECON-4410", name: "Issues in Economic Policy" },
            { code: "ECON-521", name: "Macroeconomic Analysis" },
            { code: "ECON-532", name: "Econometrics and Research Methodology II" },
            { code: "EDU-210", name: "Critical Debates in Education" },
            { code: "EDU-213", name: "Philosophy of Education" },
            { code: "EDU-216", name: "Globalization and Language" },
            { code: "EDU-224", name: "Theories of Child and Adolescent Development in Education" },
            { code: "EDU-225", name: "Motivation and Learning" },
            { code: "EDU-250", name: "Education in the Pakistani Context" },
            { code: "EDU-263", name: "Quantitative Research Methods" },
            { code: "EDU-310", name: "Learning in a Changing World: Climate, Environment & Human Capital" },
            { code: "EDU-3204", name: "Enhancing Inclusion: Exploring Autism and Intellectual Disability" },
            { code: "EDU-3208", name: "Beyond the Test: Assessment for Learning" },
            { code: "EDU-3209", name: "Mindfulness and Resilience" },
            { code: "EDU-3217", name: "Education for Emergencies" },
            { code: "EDU-332", name: "Curriculum Theory and History" },
            { code: "EDU-333", name: "Culturally Responsive Social-Emotional Learning" },
            { code: "EDU-345", name: "Practicing Leadership" },
            { code: "EDU-346", name: "Cultivating Authentic Leadership: A Journey into Self-Discovery" },
            { code: "EDU-3502", name: "Learning with Writing" },
            { code: "EDU-352", name: "Education Policy Analysis" },
            { code: "EDU-354", name: "Comparative and International Education" },
            { code: "EDU-413", name: "What does it mean to 'be educated'?" },
            { code: "EDU-426", name: "Pedagogy: Intersections of the Taught, Written, and Assessed Curriculum" },
            { code: "EDU-5202", name: "Pedagogy: Intersections of the Taught, Written, and Assessed Curriculum" },
            { code: "EDU-5203", name: "Education for Emergencies" },
            { code: "EDU-541", name: "School Effectiveness and Development" },
            { code: "EDU-561", name: "Applied Data Analysis" },
            { code: "EDU-562", name: "Data Lab" },
            { code: "EDUX-541", name: "School Effectiveness and Development" },
            { code: "EDUX-543", name: "Essential Management Tools for Aspiring Educational Leaders" },
            { code: "EDUX-561", name: "Applied Data Analysis" },
            { code: "EDUX-562", name: "Data Lab" },
            { code: "EDUX-623", name: "Effective Teaching and Learning in Higher Education" },
            { code: "EDUX-624", name: "Leadership and Administration in Higher Education" },
            { code: "EE-341", name: "Microelectronic Design" },
            { code: "EE-201", name: "Introduction to Programming" },
            { code: "EE-202", name: "Data Structures" },
            { code: "EE-220", name: "Digital Logic Circuits" },
            { code: "EE-220L", name: "Digital Logic Circuits Lab" },
            { code: "EE-241L", name: "Introductory Circuits Lab" },
            { code: "EE-242", name: "Circuits II" },
            { code: "EE-3001", name: "Junior Design Studio - Electric Vehicles" },
            { code: "EE-3002", name: "Junior Design Studio - Robotics" },
            { code: "EE-310", name: "Signals and Systems" },
            { code: "EE-315", name: "Foundations of AI and Machine Learning" },
            { code: "EE-320", name: "Computer Organization and Assembly Language" },
            { code: "EE-330", name: "Electromagnetic Fields and Waves" },
            { code: "EE-356", name: "Electrical Machines and Power Systems" },
            { code: "EE-356L", name: "Electrical Machines and Power Systems Lab" },
            { code: "EE-361", name: "Feedback Control Systems" },
            { code: "EE-361L", name: "Feedback Control Systems Lab" },
            { code: "EE-402", name: "Principles and Techniques of Data Science" },
            { code: "EE-414", name: "Deep Learning" },
            { code: "EE-416", name: "Foundations of Generative AI" },
            { code: "EE-452", name: "Power Electronics" },
            { code: "EE-452L", name: "Power Electronics Lab" },
            { code: "EE-475", name: "Network-Centric Computing" },
            { code: "EE-483", name: "Network Security" },
            { code: "EE-5001", name: "EV Design Studio" },
            { code: "EE-514", name: "Foundations of AI and Machine Learning" },
            { code: "EE-517", name: "Deep Learning" },
            { code: "EE-519", name: "Foundations of Generative AI" },
            { code: "EE-5214", name: "Verification of Digital Systems" },
            { code: "EE-522", name: "Embedded Systems" },
            { code: "EE-523", name: "VLSI Design" },
            { code: "EE-525", name: "Photovoltaic Devices" },
            { code: "EE-539", name: "Introduction to Quantum Information Science and Technology" },
            { code: "EE-5512", name: "Power System Operation and Control" },
            { code: "EE-552", name: "Power Electronics" },
            { code: "EE-552L", name: "Power Electronics Lab" },
            { code: "EE-557", name: "Electricity Markets" },
            { code: "EE-558", name: "Battery Energy Storage Systems" },
            { code: "EMBA-5012", name: "Managerial Accounting and Control Systems" },
            { code: "EMBA-5021", name: "Managerial Finance" },
            { code: "EMBA-5031", name: "Operations and Supply Chain Management" },
            { code: "EMBA-5033", name: "Innovation and Technology Management" },
            { code: "EMBA-5051", name: "Managing People" },
            { code: "EMBA-5053", name: "Leading Organizations" },
            { code: "EMBA-5111", name: "Managerial Economics" },
            { code: "EMBA-6241", name: "Islamic Ethics" },
            { code: "EMBA-6242", name: "Corporate Governance" },
            { code: "EMBA-6304", name: "Business Strategy" },
            { code: "ENGG-100", name: "Design and Measurement Lab" },
            { code: "ENGL-1111", name: "The Word and the World" },
            { code: "ENGL-2151", name: "The Anti Scooby Doo's: A Selective Survey of Detective Fiction" },
            { code: "ENGL-2152", name: "Gangs, Wizards and Soldiers: Young Adult Literature through the Ages" },
            { code: "ENGL-2811", name: "Rethinking the Politics of Harem in Literature: Women, Islam, and Gendered Spaces" },
            { code: "ENGL-3421", name: "Narrative Nonfiction - Workshop" },
            { code: "ENGL-3510", name: "Literary Theory" },
            { code: "ENGL-3712", name: "Writing Broken Homelands: Partition Literature in Pakistan, India and Palestine" },
            { code: "ENGL-3811", name: "Maternal Figures and National Fictions in the Anglophone World" },
            { code: "ENGL-3812", name: "African Literature: Women Writing Back" },
            { code: "ENV-102", name: "Introduction to Environmental Studies" },
            { code: "ENV-210", name: "Methods in Environmental Studies" },
            { code: "ENV-232", name: "Global Environmental History" },
            { code: "ENV-237", name: "Air Pollution" },
            { code: "ENV-310", name: "Quantitative Research Methods" },
            { code: "ENV-322", name: "Environmental Governance" },
            { code: "ENV-333", name: "Climate Change and Environment Policy" },
            { code: "ENV-334", name: "Politics of Water" },
            { code: "ENV-336", name: "The Politics of Resources" },
            { code: "ENV-342", name: "Environmentalism and Development" },
            { code: "ENV-443", name: "Gender and the City in South Asia" },
            { code: "FINN-100", name: "Principles of Finance" },
            { code: "FINN-200", name: "Intermediate Finance" },
            { code: "FINN-222", name: "Introduction to Mathematics of Finance" },
            { code: "FINN-242", name: "Islamic Capital Markets and Instruments" },
            { code: "FINN-243", name: "Fintech Revolution: Market Disruption and Emerging Opportunities" },
            { code: "FINN-341A", name: "Financial Institutions and Markets" },
            { code: "FINN-372", name: "Actuarial Sciences and Insurance" },
            { code: "FINN-400", name: "Applied Corporate Finance" },
            { code: "FINN-422", name: "Quantitative Finance" },
            { code: "FINN-441", name: "Islamic Banking and Finance" },
            { code: "FINN-453", name: "Financial Derivatives" },
            { code: "FINN-454", name: "Portfolio Management" },
            { code: "FMG-6201", name: "Corporate Finance and Valuation" },
            { code: "FMG-6301", name: "Investments and Portfolio Management" },
            { code: "FMG-6302", name: "Derivatives and Fixed Income" },
            { code: "FMG-6401", name: "Entrepreneurial Finance and Venture Capital" },
            { code: "GSL-102", name: "Chinese Language for Beginners (HSK Level 1)" },
            { code: "GSS-210", name: "Introduction to Gender and Sexuality Studies" },
            { code: "GSS-262", name: "Rethinking the Politics of Harem in Literature: Women, Islam, and Gendered Spaces" },
            { code: "GSS-302", name: "Feminist Theory" },
            { code: "GSS-316", name: "Gender Economics" },
            { code: "GSS-343", name: "Feminist Liberation Theologies: Interrogating the Nexus of Sex, Class, and Religion" },
            { code: "GSS-363", name: "African Literature: Women Writing Back" },
            { code: "GSS-366", name: "Gender, Nationalism, and Politics: Unpacking media master narratives in South Asia" },
            { code: "GSS-369", name: "Bad Mothers, Motherhood, and Mothering on Screen" },
            { code: "GSS-375", name: "Maternal Figures and National Fictions in the Anglophone World" },
            { code: "GSS-376", name: "(Her)Story as History: Gender, Genre and Women's Life Writings in South Asia" },
            { code: "GSS-415", name: "Gender and the City in South Asia" },
            { code: "HIST-101", name: "World Civilizations" },
            { code: "HIST-127", name: "A Peoples History of Pakistan" },
            { code: "HIST-225", name: "Bazaar Asia" },
            { code: "HIST-2313", name: "Global Environmental History" },
            { code: "HIST-263", name: "The Pakistani Drama Serial" },
            { code: "HIST-292", name: "Introduction to Sanskrit" },
            { code: "HIST-315", name: "History of Miniature Painting" },
            { code: "HIST-3223", name: "Writing Broken Homelands: Partition Literature in Pakistan, India and Palestine" },
            { code: "HIST-3324", name: "(Her)Story as History: Gender, Genre and Women's Life Writings in South Asia" },
            { code: "HIST-382", name: "Waris Shah's Heer" },
            { code: "HIST-4322", name: "World Through a Trickster's Eyes" },
            { code: "HMI-6101", name: "Health Systems Management" },
            { code: "HMI-6102", name: "Healthcare Policy, Politics and Law" },
            { code: "HMI-6103", name: "Leadership Challenges in Healthcare" },
            { code: "HMI-6201", name: "Innovation and Entrepreneurship in Healthcare" },
            { code: "HMI-6204A", name: "Advanced Analytics Healthcare - I" },
            { code: "HSS-101", name: "First Year Advising Tutorial" },
            { code: "LANG-1202", name: "Arabic for Quran" },
            { code: "LANG-1203", name: "Hindi for Non-Native Speakers" },
            { code: "LANG-1204", name: "Kashmiri I" },
            { code: "LANG-122", name: "Introduction to Balochi Language" },
            { code: "LANG-123", name: "Introduction to Punjabi Language" },
            { code: "LANG-124", name: "Introduction to Arabic Language" },
            { code: "LANG-127", name: "Introduction to Persian Language" },
            { code: "LANG-128", name: "Sindhi for Non-Sindhi Speakers" },
            { code: "LANG-129", name: "Pashto for Non-Native Speakers" },
            { code: "LANG-2208", name: "Introduction to Sanskrit" },
            { code: "LAW-101", name: "Introduction to Legal Reasoning" },
            { code: "LAW-102", name: "Introduction to Pakistan Legal System" },
            { code: "LAW-210", name: "Concept of Law" },
            { code: "LAW-223", name: "Commercial Law" },
            { code: "LAW-224", name: "Property Law" },
            { code: "LAW-225", name: "Islamic Legal Theory" },
            { code: "LAW-232", name: "Public Law" },
            { code: "LAW-320", name: "Equity, Specific Relief and Trusts" },
            { code: "LAW-3202", name: "International Corporate Finance and Insolvency Law" },
            { code: "LAW-3205", name: "International Business Transactions" },
            { code: "LAW-322", name: "Labor Law" },
            { code: "LAW-323", name: "Tax Law" },
            { code: "LAW-353", name: "Human Rights" },
            { code: "LAW-3611", name: "Family Law" },
            { code: "LAW-3912", name: "Climate Change and Environment Policy" },
            { code: "LAW-4306", name: "Judicial Review Of Public Actions: Writ Jurisdiction In Pakistan" },
            { code: "LAW-4307", name: "Foreign Investment Law and the New Silk Route" },
            { code: "LAW-4308", name: "Law, Technology and the Regulation of Social Media" },
            { code: "LAW-458", name: "Refugee Rights" },
            { code: "LAW-470", name: "Evidence" },
            { code: "LAW-472", name: "Criminal Procedure" },
            { code: "LAW-486", name: "Advanced Legal Research" },
            { code: "LAW-4906", name: "LUMS Law Clinic" },
            { code: "LAW-4909", name: "Advanced Public Law Seminar - I" },
            { code: "LAW-4924", name: "Prison Paralegal Clinic" },
            { code: "MATH-100", name: "Pre-calculus" },
            { code: "MATH-101", name: "Calculus I" },
            { code: "MATH-102", name: "Calculus II" },
            { code: "MATH-120", name: "Linear Algebra with Differential Equations" },
            { code: "MATH-120H", name: "Linear Algebra I (Honours)" },
            { code: "MATH-205", name: "Introduction to Analysis I" },
            { code: "MATH-230", name: "Probability" },
            { code: "MATH-231", name: "Statistics" },
            { code: "MATH-232", name: "Introduction to Game Theory" },
            { code: "MATH-3010", name: "Advanced Calculus" },
            { code: "MATH-310", name: "Ordinary Differential Equations" },
            { code: "MATH-320", name: "Algebra I" },
            { code: "MATH-401", name: "Functional Analysis" },
            { code: "MATH-4013", name: "Differential Geometry" },
            { code: "MATH-445", name: "Operations Research II" },
            { code: "MATH-449", name: "Quantitative Finance" },
            { code: "MATH-466", name: "General Relativity" },
            { code: "MATH-5012", name: "Advanced Differential Geometry" },
            { code: "MATH-505", name: "Advanced Functional Analysis" },
            { code: "MATH-524", name: "Advanced Quantitative Finance" },
            { code: "MATH-5300", name: "Probability and Statistical Analysis" },
            { code: "MATH-548", name: "Operational Research II" },
            { code: "MBA-5022", name: "Financial Management" },
            { code: "MBA-5101", name: "Business Ethics and Islam" },
            { code: "MBA-5111", name: "Managerial Economics" },
            { code: "MBA-5184", name: "Business Intelligence" },
            { code: "MBA-5202", name: "Managerial Accounting and Control" },
            { code: "MBA-5702", name: "Decision Analysis" },
            { code: "MBA-5703", name: "Operations Management Fundamentals" },
            { code: "MBA-5704", name: "Operations Management-Technology, Innovation and Emerging Trends" },
            { code: "MBA-5801", name: "Business Strategy" },
            { code: "MBA-5902", name: "My Startup" },
            { code: "MBA-6036", name: "AI for Business Leadership" },
            { code: "MBA-6037A", name: "Leading Projects: Navigating Inception, Planning and Execution" },
            { code: "MBA-6046", name: "Business to Business" },
            { code: "MBA-6054A", name: "Organizational Power and Politics" },
            { code: "MBA-6065", name: "Leadership and Liberal Arts" },
            { code: "MBA-6070", name: "Business, Government and Society" },
            { code: "MBA-6132", name: "Agribusiness and Value Chain Management" },
            { code: "MBA-6165", name: "Business Development and Economy" },
            { code: "MBA-6213", name: "Corporate Governance" },
            { code: "MECO-111", name: "Principles of Microeconomics" },
            { code: "MECO-121", name: "Principles of Macroeconomics" },
            { code: "MGMT-142", name: "Principles of Management" },
            { code: "MGMT-212", name: "Business Communication" },
            { code: "MGMT-242", name: "Business Ethics and Corporate Social Responsibility" },
            { code: "MGMT-243", name: "Public Administration" },
            { code: "MGMT-244", name: "Reforming The Public Sector" },
            { code: "MGMT-247", name: "Public Financial Management" },
            { code: "MGMT-252", name: "Logic and Critical Thinking" },
            { code: "MGMT-260", name: "Business Law" },
            { code: "MGMT-272", name: "International Business Transactions" },
            { code: "MGMT-273", name: "International Corporate Finance and Insolvency Law" },
            { code: "MGMT-275", name: "Foreign Investment Law and the New Silk Route" },
            { code: "MGMT-362", name: "Rethinking Policy: Critical Perspectives on Pakistan's Agricultural Development" },
            { code: "MGMT-384", name: "Entrepreneurship and Management in the Restaurant Industry" },
            { code: "MGMT-400", name: "Strategic Business Management" },
            { code: "MGMT-462", name: "Modern Thought in Social Policy" },
            { code: "MGMT-481", name: "Entrepreneurship" },
            { code: "MKTG-201", name: "Principles of Marketing" },
            { code: "MKTG-302", name: "Digital Marketing" },
            { code: "MKTG-322", name: "Sales Force Management" },
            { code: "MKTG-323", name: "Channel Management" },
            { code: "MKTG-324", name: "Integrated Marketing Communications" },
            { code: "MKTG-332", name: "Consumer Behaviour" },
            { code: "MKTG-343", name: "Marketing Models" },
            { code: "MKTG-344", name: "Data Driven Marketing" },
            { code: "MKTG-345", name: "Data Analytics for New Product Development" },
            { code: "MKTG-392", name: "Brand Management" },
            { code: "ORSC-201", name: "Organizational Behaviour" },
            { code: "ORSC-341", name: "Human Resource Management" },
            { code: "ORSC-8101", name: "Seminar in Organizational Behavior" },
            { code: "PHIL-212", name: "Plato and Aristotle" },
            { code: "PHIL-432", name: "Mohammed Iqbal and Charles Peirce" },
            { code: "PHY-104", name: "Modern Physics" },
            { code: "PHY-304", name: "Computational Physics" },
            { code: "PHY-305", name: "Electromagnetic Fields and Waves" },
            { code: "PHY-312", name: "Quantum Mechanics II" },
            { code: "PHY-332", name: "Condensed Matter Physics" },
            { code: "PHY-337", name: "Molecular Spectroscopy" },
            { code: "PHY-362", name: "Fluid Mechanics" },
            { code: "PHY-417", name: "Introduction to Quantum Information Science and Technology" },
            { code: "PHY-442", name: "General Relativity" },
            { code: "PHY-480", name: "Seminars in Physics" },
            { code: "PHY-505", name: "Computational Physics" },
            { code: "PHY-517", name: "Quantum Mechanics" },
            { code: "PHY-532", name: "Photovoltaic Devices" },
            { code: "PHY-535", name: "Advanced Condensed Matter Physics" },
            { code: "PHY-539", name: "Introduction to Quantum Field Theory" },
            { code: "PHY-612", name: "Introduction to Quantum Information Science and Technology" },
            { code: "PHY-642", name: "General Relativity" },
            { code: "PHY-712", name: "Seminars in Physics" },
            { code: "POL-320", name: "Comparative Politics" },
            { code: "POL-100", name: "Introduction to Political Science" },
            { code: "POL-203", name: "Introduction to Political Theory" },
            { code: "POL-212", name: "Class Structure in Pakistan" },
            { code: "POL-227", name: "The Politics of Conflict and Intervention in Afghanistan" },
            { code: "POL-2313", name: "Civil Society and Social Movements" },
            { code: "POL-244", name: "The Politics of Class and Markets" },
            { code: "POL-322", name: "Politics of India" },
            { code: "POL-328", name: "Politics of Pakistan" },
            { code: "POL-331", name: "Pakistan's Foreign Relations" },
            { code: "POL-338", name: "Environmental Governance" },
            { code: "POL-355", name: "Politics of Water" },
            { code: "POL-364", name: "Quantitative Research Method" },
            { code: "POL-365", name: "Gender, Nationalism, and Politics: Unpacking media master narratives in South Asia" },
            { code: "POL-373", name: "State and Sovereignty" },
            { code: "POL-375", name: "Foreign Policy Analysis" },
            { code: "POL-376", name: "Politics of International Economy" },
            { code: "POL-377", name: "Labor Law" },
            { code: "POL-378", name: "The Politics of Resources" },
            { code: "PSY-309", name: "Human Memory" },
            { code: "PSY-100", name: "Introduction to psychology and human behavior" },
            { code: "PSY-220", name: "Psychopathology" },
            { code: "PSY-224", name: "Counseling and Psychotherapy" },
            { code: "PSY-232", name: "Theories of Personality" },
            { code: "PSY-316", name: "Mind Matters: The Psychology of Intelligence and AI" },
            { code: "PSY-325", name: "Positive Psychology and The Pursuit of Happiness" },
            { code: "REL-219", name: "Islamic Legal Theory" },
            { code: "REL-337", name: "Feminist Liberation Theologies: Interrogating the Nexus of Sex, Class, and Religion" },
            { code: "REL-432", name: "Islamic Modernism in Pakistan" },
            { code: "SCI-203", name: "Air Pollution" },
            { code: "SCI-210", name: "Energy and Information" },
            { code: "SCI-305", name: "Computational Methods" },
            { code: "SCRM-6201", name: "Logistics Management" },
            { code: "SCRM-6202", name: "Supply Management" },
            { code: "SCRM-6301", name: "Retailing Strategy and Operations" },
            { code: "SOC-100", name: "Introduction to Sociology" },
            { code: "SOC-243", name: "Politics of Class and Markets" },
            { code: "SOC-244", name: "Language, Culture, and Society" },
            { code: "SOC-265", name: "Introduction to Gender and Sexuality Studies" },
            { code: "SOC-320", name: "Quantitative Research Methods" },
            { code: "SOC-321", name: "Comparative and International Education" },
            { code: "SOC-324", name: "Environmentalism and Development" },
            { code: "SOC-346", name: "The Politics of Resources" },
            { code: "SOC-347", name: "Labor Law" },
            { code: "SOC-363", name: "Feminist Theory" },
            { code: "SOC-383", name: "Racism, Migration and Displacement" },
            { code: "SOC-384", name: "Urban Transformations in the Global South" },
            { code: "SOC-463", name: "Spatial Politics and Citizenship in Urban Lives" },
            { code: "SOC-465", name: "Gender and the City in South Asia" },
            { code: "SS-100", name: "Writing and Communication" },
            { code: "SS-101", name: "Islamic Studies" },
            { code: "SS-102", name: "Pakistan Studies: Culture and Heritage" },
            { code: "SS-1312", name: "Fundamentals of Raag and Taal [Vocal and Flute]" },
            { code: "SS-187", name: "Applied Statistics for Humanities" },
            { code: "SS-2203", name: "Digital Approaches to the Humanities" },
            { code: "SS-233", name: "Media Writing" },
            { code: "SS-3302", name: "Professional Communication Skills" },
            { code: "SSE-101", name: "SSE Tutorials" },
            { code: "SWR-102", name: "Swimming for Beginners" },
            { code: "SWR-103", name: "Strength Training and Conditioning for Beginners" },
            { code: "SWR-104", name: "Basketball for beginners" },
            { code: "SWR-105", name: "Walk, Jog and Stretch for Fitness" },
            { code: "SWR-106", name: "Squash for Beginners Course" },
            { code: "SWR-107", name: "Badminton for Beginner Single and Doubles" },
            { code: "SWR-108", name: "Volleyball for Beginners Course" },
            { code: "TME-6101", name: "Tech-Entrepreneurship" },
            { code: "TME-6102", name: "Business Venture Planning" },
            { code: "TME-6201", name: "Technology, Design and Innovation Management" },
            { code: "TME-6202", name: "Technology and Operations Management" },
        ];

        let insertedCount = 0;
        for (const course of courses) {
            await ctx.db.insert("university_courses", {
                code: course.code,
                name: course.name,
                isActive: true,
            });
            insertedCount++;
        }

        return { insertedCount, totalCourses: courses.length };
    },
});
